kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "golodex-api"
  namespace: "golodex"
  labels:
    app.kubernetes.io/name: "golodex-api"
    app.kubernetes.io/managed-by: "eangeli"
    app.kubernetes.io/version: "1.0-beta"
    app.kubernetes.io/component: "db-api"
    app.kubernetes.io/part-of: "golodex"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "golodex-api"
subjects:
- kind: ServiceAccount
  name: "golodex-api"
  namespace: "golodex"
